spring.application.name=quan_ly_my_pham

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=QuanLyMyPham;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
